### PR TITLE
Add *_tut_intro.py

### PR DESCRIPTION
**Pull request by CedricDViou**
Only tested with ROACH2.
Should work with SNAP and SKARAB.

### CODE REVIEW

**Comment by AdamI75** [comment]
Hi Cedric, it looks like you are using the master branch, but I think workshop2019 still needs to be merged into the master branch. I stand corrected. The important thing to note is that the folder structure has changed from master - check it out. I will allow Jack to review and comment more.

**Comment by CedricDViou** [comment]
You are most probably right.
I should have make the changes for the "workshop 2019" branch and wait for a merge into master branch.
Right?
Should I close this now and open a new pull request for "workshop 2019"

**Comment by AdamI75** [comment]
Let's wait for Jack to respond as casper-astro is his repo. What you suggest does make sense to me, but Jack may have other ideas.

**Comment by jack-h** [comment]
Thanks for the pr.
The merge of the workshop branch into master is waiting review. @AdamI75 could you give this a one over?
Then I'll merge this in, (possibly after fixing any resulting conflicts).

**Comment by CedricDViou** [comment]
> We also have a Red Pitaya board, but you will see that when pull request 1 is merged to master? There is existing documentation that goes with the tutorials and that should also probably be updated to reflect this script.

When the Red Pitaya directory will be available, I will replicate tut_intro.py there and I'll update all tutorial documentations to link to their *_tut_intro.py.
Thanks for considering my pr.

**Comment by AdamI75** [comment]
Thanks, Cedric! This would be appreciated.

**Pull request merged**
