### PR TITLE
Updating skarab and red pitaya tutorial docs

### PR DESCRIPTION
**Pull request by mchirindo**
Fixed some broken links and updated text as required.

### CODE REVIEW

**Review by AdamI75 — CHANGES_REQUESTED** [review]
In tut_adc_dac.md: please change the following:

1) Last paragraph at the end:  "Hint: The Zynq pin outs are not the same. You will need to look at the 125-14 schematics. You will need to update the simulink yellow blocks, python blocks and red_pitaya.yaml script" to "Hint: The Zynq pin outs are not the same. You will need to look at the **122-16** schematics. You will need to update the simulink yellow blocks, python blocks and red_pitaya.yaml script".

In docs/tutorials/skarab/tut_spec.md: 

1) In parapgraph add comma before "but": "In the slx file, you'll notice a subsystem block in the top left corner of the design.  If you click into it, you'll see it contains a 40 GbE core.  That core used to instantiante the board support package and the microblaze controller**, but it is no longer the case**. The board support package and the microblaze controller are now part of the Skarab platform block. However, the 40 GbE or 1 GbE core is still required in a Skarab design for communication purposes"

There are also meant to be SKARAB 40GbE tutorial  link changes. I don't see any updates to this file. Please go through my review comments and make sure everything has been implemented, thanks.

**Comment by mchirindo** [comment]
I have pushed some updates to the devel branch on mchirindo/tutorials_devel.

**Review by AdamI75 — CHANGES_REQUESTED** [review]
Hi Mathews, I accept tut_adc_dac.md. 

1) However, tut_40gbe.md, I see you haven't changed the following link in the paragraph: 'This is the start of the logic to build up our payload. The decimation register is used to control the rate at which packets are sent. Have a look at lines 307-312 of the **Tx python script** to see how this value is calculated and used" to  https://github.com/casper-astro/tutorials_devel/tree/master/skarab/tut_40gbe/tut_40gbe.py#L307. 

2) In tut_spec.md: the comma is on the wrong side of the but - small issue, but might as well fix it :).

**Comment by mchirindo** [comment]
I have pushed further updates to the devel branch on mchirindo/tutorials_devel.

**Review by AdamI75 — APPROVED** [review]
I approve all changes and will merge. Thank you Mathews!

**Pull request merged**
